# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pemline < Formula
  desc "Inline a PEM private key into a single escaped line"
  homepage "https://github.com/faizmokh/pemline"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/faizmokh/pemline/releases/download/v0.1.0/pemline_Darwin_x86_64.tar.gz"
      sha256 "91a807e799fe39c6f9b8bb44ea43553894aa31262fb232a221a2cdf74a3ee1fb"

      define_method(:install) do
        bin.install "pemline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/faizmokh/pemline/releases/download/v0.1.0/pemline_Darwin_arm64.tar.gz"
      sha256 "c80d66264e8b4d434b4a99ac3a6fe3fa20093dab789de87654fb1b5b75b37f09"

      define_method(:install) do
        bin.install "pemline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/faizmokh/pemline/releases/download/v0.1.0/pemline_Linux_x86_64.tar.gz"
      sha256 "f73893919ef5c6cec631fc62a95f2f02ba6a43fbe52fe90c3844a2cd0da08621"
      define_method(:install) do
        bin.install "pemline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/faizmokh/pemline/releases/download/v0.1.0/pemline_Linux_arm64.tar.gz"
      sha256 "eae111eee0b8a122bc129cf3c96065f9d72e158e0fea9bc5164ce3af9e51be75"
      define_method(:install) do
        bin.install "pemline"
      end
    end
  end

  test do
    system "#{bin}/pemline", "--version"
  end
end
