# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kerja < Formula
  desc "Terminal logbook (CLI + TUI) for daily work tracking."
  homepage "https://github.com/faizmokh/kerja"
  version "0.7.7"

  on_macos do
    on_intel do
      url "https://github.com/faizmokh/kerja/releases/download/v0.7.7/kerja_0.7.7_darwin_amd64.tar.gz"
      sha256 "a744e8b79e7f13a1ba8a3ef4b41099997f798eab5ecc8ff1cfd2ff2dffe393b4"

      def install
        bin.install "kerja"
      end
    end
    on_arm do
      url "https://github.com/faizmokh/kerja/releases/download/v0.7.7/kerja_0.7.7_darwin_arm64.tar.gz"
      sha256 "27647aeb565a6c1dbd5d2c607671034af7fd17096d45faa2c5a3e9795adc5c1c"

      def install
        bin.install "kerja"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/faizmokh/kerja/releases/download/v0.7.7/kerja_0.7.7_linux_amd64.tar.gz"
        sha256 "9cb18385b58d1cf011f3fb636a4f6e9d17fd1815259dc2c1db55a9376f640cf2"

        def install
          bin.install "kerja"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/faizmokh/kerja/releases/download/v0.7.7/kerja_0.7.7_linux_arm64.tar.gz"
        sha256 "6b506b330c6566730e43d7f50a899e5ab49d26c8740fbcb3937cde5215855714"

        def install
          bin.install "kerja"
        end
      end
    end
  end

  test do
    system "#{bin}/kerja", "--version"
  end
end
