# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nuke < Formula
  desc "Clean up Xcode DerivedData and Swift Package Manager caches"
  homepage "https://github.com/faizmokh/nuke"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/faizmokh/nuke/releases/download/v0.1.0/nuke_0.1.0_darwin_amd64.tar.gz"
    sha256 "4f123731aa0b02010cc4b77c9bb8da52fbecb41be351d62cbea6175840402048"

    define_method(:install) do
      bin.install "nuke"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/faizmokh/nuke/releases/download/v0.1.0/nuke_0.1.0_darwin_arm64.tar.gz"
    sha256 "d5ba292414dc7e4167573126b60d2fb37309ec7d3c906869954cdb5811037076"

    define_method(:install) do
      bin.install "nuke"
    end
  end

  test do
    system "#{bin}/nuke", "--version"
  end
end
