# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nuke < Formula
  desc "Clean up Xcode DerivedData and Swift Package Manager caches"
  homepage "https://github.com/faizmokh/nuke"
  version "0.2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/faizmokh/nuke/releases/download/v0.2.0/nuke_0.2.0_darwin_amd64.tar.gz"
    sha256 "968cb328eaf89c155d8e532928005402a7ee66ff135ca36601207f0eb8a79571"

    define_method(:install) do
      bin.install "nuke"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/faizmokh/nuke/releases/download/v0.2.0/nuke_0.2.0_darwin_arm64.tar.gz"
    sha256 "3e18bbdba99b8ee7019c3518ad698cc18ed29beea59e3439fffe8a046568ae77"

    define_method(:install) do
      bin.install "nuke"
    end
  end

  test do
    system "#{bin}/nuke", "--version"
  end
end
