# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skmr < Formula
  desc "Manage agent skills across Codex, OpenCode, and Pi"
  homepage "https://github.com/faizmokh/skmr"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/faizmokh/skmr/releases/download/v0.6.1/skmr_0.6.1_darwin_amd64.tar.gz"
      sha256 "976eeb4324c910c3ea665e7f0497ddae86634db4581f253fda0e038a63feed40"

      define_method(:install) do
        bin.install "skmr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/faizmokh/skmr/releases/download/v0.6.1/skmr_0.6.1_darwin_arm64.tar.gz"
      sha256 "526ab0a600e6ae7b7672f0d72b0caa50fbd6174e210563043487ef419ca0db18"

      define_method(:install) do
        bin.install "skmr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/faizmokh/skmr/releases/download/v0.6.1/skmr_0.6.1_linux_amd64.tar.gz"
      sha256 "028adb68fac5892dad61b7113b6e10dd5492740b3f5c555254022d45e75d0500"
      define_method(:install) do
        bin.install "skmr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/faizmokh/skmr/releases/download/v0.6.1/skmr_0.6.1_linux_arm64.tar.gz"
      sha256 "c9634b0e32199734cedb8a9c0cacfe86fe0546ef32f97fcf48a329a23b7a5811"
      define_method(:install) do
        bin.install "skmr"
      end
    end
  end

  test do
    output = shell_output("#{bin}/skmr list --json")
    assert_match '"skills": []', output
  end
end
