# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skmr < Formula
  desc "Manage agent skills across Codex, OpenCode, and Pi"
  homepage "https://github.com/faizmokh/skmr"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/faizmokh/skmr/releases/download/v0.1.0/skmr_0.1.0_darwin_amd64.tar.gz"
      sha256 "326e8981b54733e5b52ad2ea54dd578e25060fd5e3b9733447429ce8af28c292"

      define_method(:install) do
        bin.install "skmr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/faizmokh/skmr/releases/download/v0.1.0/skmr_0.1.0_darwin_arm64.tar.gz"
      sha256 "39feb755e5674843acb96cfea3d3762fd440e17bf1293b2e55b9030781819454"

      define_method(:install) do
        bin.install "skmr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/faizmokh/skmr/releases/download/v0.1.0/skmr_0.1.0_linux_amd64.tar.gz"
      sha256 "421fb3194dd0e757cd9cbb881da205b9932e247596c9602eb127a6c8a537e924"
      define_method(:install) do
        bin.install "skmr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/faizmokh/skmr/releases/download/v0.1.0/skmr_0.1.0_linux_arm64.tar.gz"
      sha256 "076d983fe2110391503b1088cb4b780d107dfff88450feb85e853c809e7a575e"
      define_method(:install) do
        bin.install "skmr"
      end
    end
  end

  test do
    output = shell_output("#{bin}/skmr list --json")
    assert_match '"skills": []', output
  end
end
