# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skmr < Formula
  desc "Manage agent skills across Codex, OpenCode, and Pi"
  homepage "https://github.com/faizmokh/skmr"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/faizmokh/skmr/releases/download/v0.5.0/skmr_0.5.0_darwin_amd64.tar.gz"
      sha256 "aa148c4567b36f4098d736985876f51e10338bd297431e4254f8e034f29f0752"

      define_method(:install) do
        bin.install "skmr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/faizmokh/skmr/releases/download/v0.5.0/skmr_0.5.0_darwin_arm64.tar.gz"
      sha256 "d7f873897d1b3b465554f2ea55f1854289a1a88b4cbf30f91d677bdb3ddc1dae"

      define_method(:install) do
        bin.install "skmr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/faizmokh/skmr/releases/download/v0.5.0/skmr_0.5.0_linux_amd64.tar.gz"
      sha256 "dbb445f913465d0e499746197a2e026644f6901c828d77c510076c8419183012"
      define_method(:install) do
        bin.install "skmr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/faizmokh/skmr/releases/download/v0.5.0/skmr_0.5.0_linux_arm64.tar.gz"
      sha256 "0b5b5c9572a726520596ade6c0885a9fcff2f24f97c0ce2310d6a7220e6969a1"
      define_method(:install) do
        bin.install "skmr"
      end
    end
  end

  test do
    output = shell_output("#{bin}/skmr list --json")
    assert_match '"skills": []', output
  end
end
